# Лабораторная работа №1
## Выполнил студент группы БВТ2002 Гамарник Владимир Владимирович
### Задание №1
Выведите "Hello, World!"

In [4]:
print("Hello, World!")

Hello, World!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер матрицы, а min_lim и max_lim - минимальное и максимальное значение для генерируемого числа. По умолчанию при отсутствии параметров принимать следующие значения:
m = 50
n = 50
min_limit = -250
max_limit = 1000 + (номер своего варианта)

In [14]:
import numpy as np
m = int(input())
n = int(input())
min_limit = int(input())
max_limit = int(input())
if(m == ''):
  m = 50
if(n == ''):
  n = 50
if(min_limit == ''):
  min_limit = -250
if(max_limit == ''):
  max_limit = 1000 + 5
matrix = np.random.randint(min_limit, max_limit, (m, n))
print(matrix)

10
10
0
100
[[74  5  0 83 80 79 66 26 59 33]
 [96 25 44 94 34  0 98 33 47 35]
 [82 74 73 33 78 58 42 80 52  5]
 [86 53 72 43 21 19 63 35 52 47]
 [ 1 40 99 75 29 65 24 77 73 59]
 [87 31 12 97 84 20 84 40 20 58]
 [89 11  0 31 66 57 56 67 22 38]
 [45  7 17 59 67 11 93 87 78 27]
 [35  3 58 94 56 33 56 86 17 42]
 [89 93 85 23 74 87 35 89 13 93]]


### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со временем стандартной функции сортировки. Испытания проводить на сгенерированных матрицах 
Методы: Выбором, Вставкой, Обменом, Шелла, Турнирная, Быстрая, сортировка, Пирамидальная.

1. Сортировка выбором

In [15]:
from random import randint
 
 
def sel_sort(array):
    for i in range(len(array) - 1):
        m = i
        j = i + 1
        while j < len(array):
            if array[j] < array[m]:
                m = j
            j = j + 1
        array[i], array[m] = array[m], array[i]
 
 
a = []
for i in range(10):
    a.append(randint(1, 99))
 
print(a)
sel_sort(a)
print(a)

[32, 23, 26, 41, 77, 61, 74, 43, 25, 36]
[23, 25, 26, 32, 36, 41, 43, 61, 74, 77]


2. Сортировка Вставкой

In [1]:
def insertion_sort(alist):
    for i in range(1, len(alist)):
        temp = alist[i]
        j = i - 1
        while (j >= 0 and temp < alist[j]):
            alist[j + 1] = alist[j]
            j = j - 1
        alist[j + 1] = temp
 
 
alist = input('Enter the list of numbers: ').split()
alist = [int(x) for x in alist]
insertion_sort(alist)
print('Sorted list: ', end='')
print(alist)

KeyboardInterrupt: ignored

3. Сортировка Обменом

In [20]:
from random import randint
 
N = 10
a = []
for i in range(N):
    a.append(randint(1, 99))
print(a)
 
 
for i in range(N-1):
    for j in range(N-i-1):
        if a[j] > a[j+1]:
            a[j], a[j+1] = a[j+1], a[j]
 
print(a)

[28, 92, 49, 89, 5, 3, 74, 45, 29, 5]
[3, 5, 5, 28, 29, 45, 49, 74, 89, 92]


4. Сортировка Шелла

In [22]:
def shellSort(alist):
    sublistcount = len(alist)//2
    while sublistcount > 0:

      for startposition in range(sublistcount):
        gapInsertionSort(alist,startposition,sublistcount)

      print("After increments of size",sublistcount,
                                   "The list is",alist)

      sublistcount = sublistcount // 2

def gapInsertionSort(alist,start,gap):
    for i in range(start+gap,len(alist),gap):

        currentvalue = alist[i]
        position = i

        while position>=gap and alist[position-gap]>currentvalue:
            alist[position]=alist[position-gap]
            position = position-gap

        alist[position]=currentvalue

alist = [54,26,93,17,77,31,44,55,20]
shellSort(alist)
print(alist)


After increments of size 4 The list is [20, 26, 44, 17, 54, 31, 93, 55, 77]
After increments of size 2 The list is [20, 17, 44, 26, 54, 31, 77, 55, 93]
After increments of size 1 The list is [17, 20, 26, 31, 44, 54, 55, 77, 93]
[17, 20, 26, 31, 44, 54, 55, 77, 93]
